### ISSUE TITLE
keep getting errors

### ISSUE THREAD

**Issue by sgavade** [addmitriev/grunt-browser-extension#1]
hi,

I keep getting "Warning: Object #<Object> has no method 'isString' Use --force to continue." every time I run this.  I am running it with the default options from your example.

Any clues?

Thanks,
Sameer

**Comment by opcode0x** [comment]
@sgavade Maybe your nodejs package doesn't contain [ `util`](https://www.npmjs.com/package/util) module.

Try to install it globally 

``` sh
npm install -g util
```

I will include this package in dependencies in next version! Thank for issue, hope advice will help

**Comment by opcode0x** [comment]
@sgavade I've updated npm package to version 0.2.1, try to reinstall it and run again. Simple tests run succesful now!

**Comment by sgavade** [comment]
Thanks. I will try this
